# GET the home route
GET http://localhost:8080/

###

# GET all locations
GET http://localhost:3000/api/words

###

# GET a specific location by ID
GET http://localhost:8080/api/locations/10

###

# DELETE a location by ID
DELETE http://localhost:8080/api/locations/32

###

# POST a new location
POST http://localhost:8080/api/locations/
Content-Type: application/json

{
  "latitude": 60,
  "longitude": 60
}

###

# PUT to update a location by ID
# Replace ID and values as needed
PUT http://localhost:8080/api/locations/1
Content-Type: application/json

{
  "latitude": 70,
  "longitude": 70
}

###

# PATCH to partially update a location by ID
# Replace ID and values as needed
PATCH http://localhost:8080/api/locations/10
Content-Type: application/json

{
  "longitude": 65
}

###

# GET all locations with FILTER (e.g., filter by latitude)
# Replace query parameters as needed
GET http://localhost:8080/api/locations?latitude=9

###

# GET all locations with SORT (e.g., sort by latitude)
# Replace query parameters as needed
GET http://localhost:8080/api/locations?sort=latitude